#!/usr/bin/env node
/**
 * build-blog.js - static blog generator for jeryn.me
 *
 * Reads JSON posts from blog/posts/*.json and generates:
 *   blog/<slug>.html   - one static, fully SEO-tagged page per post
 *   blog/index.html    - the post listing
 *   blog/feed.xml      - RSS 2.0 feed
 *   sitemap.xml        - blog entries inserted between <!-- blog:start/end --> markers
 *
 * Usage: node scripts/build-blog.js
 *
 * Post schema (blog/posts/my-post.json — filename becomes the slug):
 * {
 *   "title":       "Post title",
 *   "description": "1-2 sentence summary. Shows in Google results and the index.",
 *   "date":        "2026-07-21",
 *   "updated":     "2026-07-22",          // optional
 *   "tags":        ["philosophy", "cs"],  // optional
 *   "image":       "/screen_shots/x.png", // optional social-card image
 *   "draft":       true,                  // optional, skips the post
 *   "content":     [ ...blocks ]          // same block format as the docs system
 * }
 *
 * Conten blocks (see blog/posts/_template.json for a live example of each):
 *   {"title": "..."} {"label": "..."} {"smallLabel": "..."} {"text": "..."}
 *   {"description": "..."} {"list": [...]} {"numberedList": [...]}
 *   {"quote": {"text": "...", "by": "..."}} {"divider": true}
 *   {"image": {"src": "...", "alt": "...", "caption": "...", "size": "60%"}}
 *   {"link": {"href": "...", "text": "..."}}
 *   {"codeSnippet": {"type": "go", "name": "main.go", "data": "..."}}
 *   {"html": "<raw html escape hatch>"}
 */

const fs = require("fs");
const path = require("path");

const SITE = "https://jeryn.me";
const BLOG_TITLE = "Jeryn Vicari - Blog";
const BLOG_DESCRIPTION =
    "Notes on what I'm learning and researching - systems programming, computer science, and philosophy.";
const AUTHOR = {
    name: "Jeryn Vicari",
    url: `${SITE}/`,
    sameAs: [
        "https://www.linkedin.com/in/jerynv",
        "https://github.com/jerynv",
        "https://www.youtube.com/channel/UCCJuYKz_dgU3bCypNugq2kA",
    ],
};
const DEFAULT_IMAGE = `${SITE}/portrait.jpg`;
const GENERATED_MARK = "<!-- generated by build-blog.js -->";

const ROOT = path.join(__dirname, "..");
const POSTS_DIR = path.join(ROOT, "blog", "posts");
const OUT_DIR = path.join(ROOT, "blog");
const SITEMAP_PATH = path.join(ROOT, "sitemap.xml");

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function escapeHtml(str) {
    return String(str)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");
}

function escapeXml(str) {
    return String(str)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&apos;");
}

function stripTags(html) {
    return String(html).replace(/<[^>]*>/g, " ");
}

function fmtDate(iso) {
    const [y, m, d] = iso.split("-").map(Number);
    return `${MONTHS[m - 1]} ${d}, ${y}`;
}

function rfc822(iso) {
    return new Date(`${iso}T12:00:00Z`).toUTCString();
}

function fail(msg) {
    console.error(`build-blog: ${msg}`);
    process.exit(1);
}

// ---------------------------------------------------------------- load posts

function loadPosts() {
    if (!fs.existsSync(POSTS_DIR)) fail(`missing posts directory ${POSTS_DIR}`);
    const posts = [];
    for (const file of fs.readdirSync(POSTS_DIR).sort()) {
        if (!file.endsWith(".json") || file.startsWith("_")) continue;
        const raw = fs.readFileSync(path.join(POSTS_DIR, file), "utf8");
        let post;
        try {
            post = JSON.parse(raw);
        } catch (e) {
            fail(`${file}: invalid JSON - ${e.message}`);
        }
        if (post.draft) {
            console.log(`skip (draft): ${file}`);
            continue;
        }
        const slug = file.replace(/\.json$/, "");
        if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug))
            fail(`${file}: filename must be kebab-case (lowercase letters, digits, hyphens)`);
        for (const field of ["title", "description", "date", "content"]) {
            if (!post[field]) fail(`${file}: missing required field "${field}"`);
        }
        if (!/^\d{4}-\d{2}-\d{2}$/.test(post.date)) fail(`${file}: date must be YYYY-MM-DD`);
        if (post.updated && !/^\d{4}-\d{2}-\d{2}$/.test(post.updated))
            fail(`${file}: updated must be YYYY-MM-DD`);
        if (!Array.isArray(post.content)) fail(`${file}: content must be an array of blocks`);
        posts.push({ ...post, slug, tags: post.tags || [], url: `${SITE}/blog/${slug}.html` });
    }
    // newest first; ties broken by slug so the order is deterministic
    posts.sort((a, b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
    return posts;
}

// ------------------------------------------------------------- block renderer

function renderBlocks(blocks, slug) {
    let html = "";
    let words = 0;
    let hasCode = false;

    const countWords = (text) => {
        words += stripTags(text).split(/\s+/).filter(Boolean).length;
    };

    for (const block of blocks) {
        const key = Object.keys(block)[0];
        const value = block[key];
        switch (key) {
            case "title":
                countWords(value);
                html += `<h2>${value}</h2>\n`;
                break;
            case "label":
                countWords(value);
                html += `<h2 class="label">${value}</h2>\n`;
                break;
            case "smallLabel":
                countWords(value);
                html += `<h3 class="small-label">${value}</h3>\n`;
                break;
            case "description":
                countWords(value);
                html += `<p class="lede">${value}</p>\n`;
                break;
            case "text":
                countWords(value);
                html += `<p>${value}</p>\n`;
                break;
            case "list":
            case "numberedList": {
                const tag = key === "list" ? "ul" : "ol";
                const items = value.map((item) => {
                    countWords(item);
                    return `<li>${item}</li>`;
                });
                html += `<${tag}>\n${items.join("\n")}\n</${tag}>\n`;
                break;
            }
            case "quote": {
                const text = typeof value === "string" ? value : value.text;
                countWords(text);
                html += `<blockquote><p>${text}</p>`;
                if (value.by) html += `<cite>${escapeHtml(value.by)}</cite>`;
                html += `</blockquote>\n`;
                break;
            }
            case "divider":
                html += `<hr />\n`;
                break;
            case "image": {
                const size = value.size ? ` style="max-width:${escapeHtml(value.size)}"` : "";
                html += `<figure><img src="${escapeHtml(value.src)}" alt="${escapeHtml(value.alt || "")}" loading="lazy"${size} />`;
                if (value.caption) html += `<figcaption>${value.caption}</figcaption>`;
                html += `</figure>\n`;
                break;
            }
            case "link":
                html += `<p><a href="${escapeHtml(value.href)}" target="_blank" rel="noopener">${escapeHtml(value.text)}</a></p>\n`;
                break;
            case "codeSnippet": {
                hasCode = true;
                const lang = escapeHtml(value.type || "plaintext");
                const name = escapeHtml(value.name || value.type || "code");
                html += `<div class="code-snippet"><div class="code-snippet-info"><span>${name}</span><span class="copy-button" role="button" tabindex="0">Copy</span></div><pre><code class="language-${lang}">${escapeHtml(value.data)}</code></pre></div>\n`;
                break;
            }
            case "html":
                html += `${value}\n`;
                break;
            default:
                fail(`${slug}: unknown block type "${key}"`);
        }
    }
    return { html, words, hasCode };
}

// ---------------------------------------------------------------- page shell

function headCommon() {
    return `    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/x-icon" href="/j.ico">
    <link rel="alternate" type="application/rss+xml" title="${escapeHtml(BLOG_TITLE)}" href="${SITE}/blog/feed.xml">
    <link rel="stylesheet" href="/css/root.css">
    <link rel="stylesheet" href="/css/blog.css">
    <script src="/scripts/mode.js"></script>
    <script defer src="/scripts/index.js"></script>`;
}

function renderPostPage(post, prev, next) {
    const { html: contentHtml, words, hasCode } = renderBlocks(post.content, post.slug);
    const minutes = Math.max(1, Math.round(words / 200));
    const updated = post.updated || post.date;
    const image = post.image ? SITE + post.image : DEFAULT_IMAGE;
    const keywords = [...post.tags, "Jeryn Vicari", "blog"].join(", ");

    const jsonLd = {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        headline: post.title,
        description: post.description,
        url: post.url,
        mainEntityOfPage: { "@type": "WebPage", "@id": post.url },
        datePublished: post.date,
        dateModified: updated,
        author: { "@type": "Person", name: AUTHOR.name, url: AUTHOR.url, sameAs: AUTHOR.sameAs },
        publisher: { "@type": "Person", name: AUTHOR.name, url: AUTHOR.url },
        image,
        keywords,
        wordCount: words,
        timeRequired: `PT${minutes}M`,
        isPartOf: { "@type": "Blog", "@id": `${SITE}/blog/`, name: BLOG_TITLE },
        inLanguage: "en-US",
    };

    const breadcrumbs = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        itemListElement: [
            { "@type": "ListItem", position: 1, name: "Home", item: `${SITE}/` },
            { "@type": "ListItem", position: 2, name: "Blog", item: `${SITE}/blog/` },
            { "@type": "ListItem", position: 3, name: post.title, item: post.url },
        ],
    };

    const tagsHtml = post.tags.length
        ? `<div class="tags">${post.tags.map((t) => `<span class="tag">${escapeHtml(t)}</span>`).join("")}</div>`
        : "";

    const navLinks = [];
    if (next) navLinks.push(`<a class="post-nav-link" href="/blog/${next.slug}.html" rel="next"> <-- ${escapeHtml(next.title)}</a>`);
    navLinks.push(`<a class="post-nav-link" href="/blog/">All posts</a>`);
    if (prev) navLinks.push(`<a class="post-nav-link" href="/blog/${prev.slug}.html" rel="prev">${escapeHtml(prev.title)} --></a>`);

    const highlight = hasCode
        ? `\n    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <script defer src="/scripts/blog.js"></script>`
        : "";

    const updatedLine =
        post.updated && post.updated !== post.date
            ? ` &middot; updated <time datetime="${post.updated}">${fmtDate(post.updated)}</time>`
            : "";

    return `<!DOCTYPE html>
${GENERATED_MARK}
<html lang="en">

<head>
${headCommon()}
    <title>${escapeHtml(post.title)} - Jeryn Vicari</title>
    <link rel="canonical" href="${post.url}">

    <meta name="description" content="${escapeHtml(post.description)}" />
    <meta name="keywords" content="${escapeHtml(keywords)}">
    <meta name="author" content="${escapeHtml(AUTHOR.name)}">

    <!-- Open Graph -->
    <meta property="og:type" content="article">
    <meta property="og:title" content="${escapeHtml(post.title)}">
    <meta property="og:description" content="${escapeHtml(post.description)}">
    <meta property="og:url" content="${post.url}">
    <meta property="og:site_name" content="${escapeHtml(AUTHOR.name)}">
    <meta property="og:image" content="${escapeHtml(image)}">
    <meta property="article:published_time" content="${post.date}">
    <meta property="article:modified_time" content="${updated}">
    <meta property="article:author" content="${AUTHOR.url}">
${post.tags.map((t) => `    <meta property="article:tag" content="${escapeHtml(t)}">`).join("\n")}

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="${escapeHtml(post.title)}">
    <meta name="twitter:description" content="${escapeHtml(post.description)}">
    <meta name="twitter:image" content="${escapeHtml(image)}">
${highlight}

    <!-- Structured Data -->
    <script type="application/ld+json">
${JSON.stringify(jsonLd, null, 2)}
    </script>
    <script type="application/ld+json">
${JSON.stringify(breadcrumbs, null, 2)}
    </script>
</head>

<body>
    <header class="header"></header>
    <main>
        <article class="post">
            <header class="post-header">
                <h1>${escapeHtml(post.title)}</h1>
                <p class="post-meta">
                    <time datetime="${post.date}">${fmtDate(post.date)}</time>${updatedLine}
                    &middot; ${minutes} min read
                </p>
                ${tagsHtml}
            </header>
            <div class="post-content">
${contentHtml}            </div>
            <footer class="post-footer">
                <nav class="post-nav">
                    ${navLinks.join("\n                    ")}
                </nav>
            </footer>
        </article>
    </main>
</body>

</html>
`;
}

function renderIndexPage(posts) {
    const jsonLd = {
        "@context": "https://schema.org",
        "@type": "Blog",
        "@id": `${SITE}/blog/`,
        name: BLOG_TITLE,
        description: BLOG_DESCRIPTION,
        url: `${SITE}/blog/`,
        inLanguage: "en-US",
        author: { "@type": "Person", name: AUTHOR.name, url: AUTHOR.url, sameAs: AUTHOR.sameAs },
        blogPost: posts.map((p) => ({
            "@type": "BlogPosting",
            headline: p.title,
            description: p.description,
            url: p.url,
            datePublished: p.date,
            dateModified: p.updated || p.date,
            author: { "@type": "Person", name: AUTHOR.name, url: AUTHOR.url },
            keywords: p.tags.join(", "),
        })),
    };

    const breadcrumbs = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        itemListElement: [
            { "@type": "ListItem", position: 1, name: "Home", item: `${SITE}/` },
            { "@type": "ListItem", position: 2, name: "Blog", item: `${SITE}/blog/` },
        ],
    };

    const byYear = new Map();
    for (const p of posts) {
        const year = p.date.slice(0, 4);
        if (!byYear.has(year)) byYear.set(year, []);
        byYear.get(year).push(p);
    }

    let listHtml = "";
    for (const [year, yearPosts] of byYear) {
        listHtml += `            <section class="post-year">\n                <h2>${year}</h2>\n`;
        for (const p of yearPosts) {
            const tags = p.tags.length
                ? `<div class="tags">${p.tags.map((t) => `<span class="tag">${escapeHtml(t)}</span>`).join("")}</div>`
                : "";
            listHtml += `                <a class="post-card" href="/blog/${p.slug}.html">
                    <time class="post-card-date" datetime="${p.date}">${fmtDate(p.date)}</time>
                    <div class="post-card-body">
                        <h3>${escapeHtml(p.title)}</h3>
                        <p>${escapeHtml(p.description)}</p>
                        ${tags}
                    </div>
                </a>\n`;
        }
        listHtml += `            </section>\n`;
    }

    if (!posts.length) listHtml = `            <p class="blog-empty">Nothing here yet - first post coming soon.</p>\n`;

    return `<!DOCTYPE html>
${GENERATED_MARK}
<html lang="en">

<head>
${headCommon()}
    <title>Blog - Jeryn Vicari</title>
    <link rel="canonical" href="${SITE}/blog/">

    <meta name="description" content="${escapeHtml(BLOG_DESCRIPTION)}" />
    <meta name="keywords" content="Jeryn Vicari, blog, computer science, systems programming, philosophy, research notes">
    <meta name="author" content="${escapeHtml(AUTHOR.name)}">

    <!-- Open Graph -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="Blog - Jeryn Vicari">
    <meta property="og:description" content="${escapeHtml(BLOG_DESCRIPTION)}">
    <meta property="og:url" content="${SITE}/blog/">
    <meta property="og:site_name" content="${escapeHtml(AUTHOR.name)}">
    <meta property="og:image" content="${DEFAULT_IMAGE}">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Blog - Jeryn Vicari">
    <meta name="twitter:description" content="${escapeHtml(BLOG_DESCRIPTION)}">
    <meta name="twitter:image" content="${DEFAULT_IMAGE}">

    <!-- Structured Data -->
    <script type="application/ld+json">
${JSON.stringify(jsonLd, null, 2)}
    </script>
    <script type="application/ld+json">
${JSON.stringify(breadcrumbs, null, 2)}
    </script>
</head>

<body>
    <header class="header"></header>
    <main>
        <h1>Blog</h1>
        <p class="blog-intro">${escapeHtml(BLOG_DESCRIPTION)} Subscribe via <a href="/blog/feed.xml">RSS</a>.</p>
        <div class="post-list">
${listHtml}        </div>
    </main>
</body>

</html>
`;
}

// ----------------------------------------------------------------- rss + map

function renderFeed(posts) {
    const newest = posts[0] ? rfc822(posts[0].updated || posts[0].date) : rfc822("2026-01-01");
    const items = posts
        .map((p) => {
            const categories = p.tags.map((t) => `            <category>${escapeXml(t)}</category>`).join("\n");
            return `        <item>
            <title>${escapeXml(p.title)}</title>
            <link>${p.url}</link>
            <guid isPermaLink="true">${p.url}</guid>
            <pubDate>${rfc822(p.date)}</pubDate>
            <description>${escapeXml(p.description)}</description>
${categories}
        </item>`;
        })
        .join("\n");

    return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>${escapeXml(BLOG_TITLE)}</title>
        <link>${SITE}/blog/</link>
        <atom:link href="${SITE}/blog/feed.xml" rel="self" type="application/rss+xml" />
        <description>${escapeXml(BLOG_DESCRIPTION)}</description>
        <language>en-us</language>
        <lastBuildDate>${newest}</lastBuildDate>
${items}
    </channel>
</rss>
`;
}

function updateSitemap(posts) {
    if (!fs.existsSync(SITEMAP_PATH)) {
        console.warn("build-blog: sitemap.xml not found, skipping sitemap update");
        return;
    }
    let sitemap = fs.readFileSync(SITEMAP_PATH, "utf8");
    const newestDate = posts[0] ? posts[0].updated || posts[0].date : "2026-01-01";
    let entries = `<!-- blog:start (managed by scripts/build-blog.js, do not edit by hand) -->\n`;
    entries += `<url>\n<loc>${SITE}/blog/</loc>\n<lastmod>${newestDate}T00:00:00+00:00</lastmod>\n<priority>0.90</priority>\n</url>\n`;
    for (const p of posts) {
        entries += `<url>\n<loc>${p.url}</loc>\n<lastmod>${p.updated || p.date}T00:00:00+00:00</lastmod>\n<priority>0.80</priority>\n</url>\n`;
    }
    entries += `<!-- blog:end -->`;

    if (sitemap.includes("<!-- blog:start")) {
        sitemap = sitemap.replace(/<!-- blog:start[\s\S]*?<!-- blog:end -->/, entries);
    } else {
        sitemap = sitemap.replace("</urlset>", `${entries}\n</urlset>`);
    }
    fs.writeFileSync(SITEMAP_PATH, sitemap);
}

// ---------------------------------------------------------------------- main

function main() {
    const posts = loadPosts();

    fs.mkdirSync(OUT_DIR, { recursive: true });

    // remove generated pages whose source post no longer exists
    const validNames = new Set(["index.html", ...posts.map((p) => `${p.slug}.html`)]);
    for (const file of fs.readdirSync(OUT_DIR)) {
        if (!file.endsWith(".html") || validNames.has(file)) continue;
        const existing = fs.readFileSync(path.join(OUT_DIR, file), "utf8");
        if (existing.includes(GENERATED_MARK)) {
            fs.unlinkSync(path.join(OUT_DIR, file));
            console.log(`removed orphan: blog/${file}`);
        }
    }

    posts.forEach((post, i) => {
        const prev = posts[i + 1] || null; // older
        const next = posts[i - 1] || null; // newer
        fs.writeFileSync(path.join(OUT_DIR, `${post.slug}.html`), renderPostPage(post, prev, next));
        console.log(`built: blog/${post.slug}.html`);
    });

    fs.writeFileSync(path.join(OUT_DIR, "index.html"), renderIndexPage(posts));
    console.log("built: blog/index.html");

    fs.writeFileSync(path.join(OUT_DIR, "feed.xml"), renderFeed(posts));
    console.log("built: blog/feed.xml");

    updateSitemap(posts);
    console.log("updated: sitemap.xml");

    console.log(`done - ${posts.length} post(s)`);
}

main();
